In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/Users/sami/Documents/CS Postgrad/IDS/COIY065D7_Anomaly-Based-IDS/Data/entire_dataset.csv")

In [4]:
print(df.duplicated().sum())

25082121

In [18]:
df = df.drop_duplicates()

In [19]:
print(df.duplicated().sum())

0

In [20]:
df["binary_label"] = df["label"].apply(
    lambda x: 0 if x == "Benign_Final" 
    else 1
)

In [21]:
df["binary_label"].value_counts()

binary_label
1    20600639
0     1093940
Name: count, dtype: int64

In [22]:
df["binary_label"].value_counts(normalize = True)

binary_label
1    0.949575
0    0.050425
Name: proportion, dtype: float64

In [23]:
df.rename(columns = {"label": "attack_type"}, inplace = True)

In [24]:
df.isnull().sum()

Header_Length        0
Protocol Type        0
Time_To_Live         0
Rate                 0
fin_flag_number      1
syn_flag_number      1
rst_flag_number      1
psh_flag_number      1
ack_flag_number      1
ece_flag_number      1
cwr_flag_number      1
ack_count            1
syn_count            1
fin_count            1
rst_count            1
HTTP                 1
HTTPS                1
DNS                  1
Telnet               1
SMTP                 1
SSH                  1
IRC                  1
TCP                  1
UDP                  1
DHCP                 1
ARP                  1
ICMP                 1
IGMP                 1
IPv                  1
LLC                  1
Tot sum              1
Min                  1
Max                  1
AVG                  2
Std                418
Tot size             3
IAT                  3
Number               3
Variance           419
attack_type          0
binary_label         0
dtype: int64

In [25]:
df = df.dropna()

In [26]:
num_df = df.select_dtypes(include = [np.number])

In [27]:
np.isinf(num_df).sum()

Header_Length        0
Protocol Type        0
Time_To_Live         0
Rate               182
fin_flag_number      0
syn_flag_number      0
rst_flag_number      0
psh_flag_number      0
ack_flag_number      0
ece_flag_number      0
cwr_flag_number      0
ack_count            0
syn_count            0
fin_count            0
rst_count            0
HTTP                 0
HTTPS                0
DNS                  0
Telnet               0
SMTP                 0
SSH                  0
IRC                  0
TCP                  0
UDP                  0
DHCP                 0
ARP                  0
ICMP                 0
IGMP                 0
IPv                  0
LLC                  0
Tot sum              0
Min                  0
Max                  0
AVG                  0
Std                  0
Tot size             0
IAT                  0
Number               0
Variance             0
binary_label         0
dtype: int64

In [28]:
df.replace([np.inf, -np.inf], np.nan, inplace = True)
df = df.dropna()

In [29]:
df.dtypes

Header_Length      float64
Protocol Type        int64
Time_To_Live       float64
Rate               float64
fin_flag_number    float64
syn_flag_number    float64
rst_flag_number    float64
psh_flag_number    float64
ack_flag_number    float64
ece_flag_number    float64
cwr_flag_number    float64
ack_count          float64
syn_count          float64
fin_count          float64
rst_count          float64
HTTP               float64
HTTPS              float64
DNS                float64
Telnet             float64
SMTP               float64
SSH                float64
IRC                float64
TCP                float64
UDP                float64
DHCP               float64
ARP                float64
ICMP               float64
IGMP               float64
IPv                float64
LLC                float64
Tot sum            float64
Min                float64
Max                float64
AVG                float64
Std                float64
Tot size           float64
IAT                float64
Number             float64
Variance           float64
attack_type         object
binary_label         int64
dtype: object

In [30]:
df.describe()

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,Tot sum,Min,Max,AVG,Std,Tot size,IAT,Number,Variance,binary_label
count,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,...,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07,2.169398e+07
mean,1.406743e+01,1.120694e+01,6.942047e+01,1.922094e+04,6.201853e-02,1.962902e-01,7.446739e-02,9.363295e-02,1.696226e-01,6.113646e-05,...,1.616504e+04,9.755847e+01,4.072353e+02,2.089208e+02,8.928235e+01,2.089208e+02,2.278948e-02,9.045092e+01,7.411471e+04,9.495770e-01
std,9.106782e+00,1.151040e+01,2.073571e+01,3.106486e+04,2.352177e-01,3.856074e-01,2.459474e-01,2.589374e-01,3.370282e-01,2.980959e-03,...,2.326019e+04,1.483569e+02,8.179917e+02,3.163960e+02,2.571836e+02,3.163960e+02,3.096908e+01,2.766064e+01,5.690999e+05,2.188162e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,1.272070e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.200000e+02,4.200000e+01,4.600000e+01,4.600000e+01,0.000000e+00,4.600000e+01,-1.781798e-02,2.000000e+00,0.000000e+00,0.000000e+00
25%,7.920000e+00,6.000000e+00,6.400000e+01,4.453167e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.000000e+03,6.000000e+01,6.000000e+01,6.000000e+01,0.000000e+00,6.000000e+01,3.797054e-05,1.000000e+02,0.000000e+00,1.000000e+00
50%,1.980000e+01,6.000000e+00,6.400000e+01,1.263421e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.014000e+03,6.000000e+01,7.800000e+01,6.030000e+01,1.400000e+00,6.030000e+01,8.079052e-05,1.000000e+02,1.960000e+00,1.000000e+00
75%,2.000000e+01,1.700000e+01,6.573000e+01,2.730667e+04,0.000000e+00,1.000000e-02,0.000000e+00,1.000000e-02,3.000000e-02,0.000000e+00,...,6.732000e+03,6.000000e+01,4.410000e+02,1.397000e+02,3.020596e+01,1.397000e+02,2.280498e-04,1.000000e+02,9.124000e+02,1.000000e+00
max,6.000000e+01,4.700000e+01,2.550000e+02,1.572864e+07,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,3.164920e+05,7.306000e+03,5.219400e+04,9.430300e+03,1.165540e+04,9.430300e+03,7.861200e+04,1.000000e+02,1.358485e+08,1.000000e+00

In [31]:
df.to_csv("cleaned_dataset.csv", index = False)

In [32]:
print(df.columns)
df.head()

Index(['Header_Length', 'Protocol Type', 'Time_To_Live', 'Rate',
       'fin_flag_number', 'syn_flag_number', 'rst_flag_number',
       'psh_flag_number', 'ack_flag_number', 'ece_flag_number',
       'cwr_flag_number', 'ack_count', 'syn_count', 'fin_count', 'rst_count',
       'HTTP', 'HTTPS', 'DNS', 'Telnet', 'SMTP', 'SSH', 'IRC', 'TCP', 'UDP',
       'DHCP', 'ARP', 'ICMP', 'IGMP', 'IPv', 'LLC', 'Tot sum', 'Min', 'Max',
       'AVG', 'Std', 'Tot size', 'IAT', 'Number', 'Variance', 'attack_type',
       'binary_label'],
      dtype='object')

,Header_Length,Protocol Type,Time_To_Live,Rate,fin_flag_number,syn_flag_number,rst_flag_number,psh_flag_number,ack_flag_number,ece_flag_number,...,Min,Max,AVG,Std,Tot size,IAT,Number,Variance,attack_type,binary_label
0,8.0,17,64.00,27800.782130,0.00,0.00,0.0,0.0,0.00,0.0,...,162.0,162.0,162.00,0.000000,162.00,0.000036,100.0,0.000000,DoS-UDP_Flood,1
1,8.0,17,64.00,22451.043785,0.00,0.00,0.0,0.0,0.00,0.0,...,162.0,162.0,162.00,0.000000,162.00,0.000045,100.0,0.000000,DoS-UDP_Flood,1
2,8.0,17,65.91,4002.885992,0.00,0.00,0.0,0.0,0.00,0.0,...,162.0,230.0,162.68,6.800000,162.68,0.000250,100.0,46.240000,DoS-UDP_Flood,1
3,8.0,17,64.00,7530.709566,0.00,0.00,0.0,0.0,0.00,0.0,...,162.0,162.0,162.00,0.000000,162.00,0.000133,100.0,0.000000,DoS-UDP_Flood,1
4,8.8,17,65.91,4367.383404,0.01,0.01,0.0,0.0,0.02,0.0,...,66.0,230.0,158.96,19.679205,158.96,0.000229,100.0,387.271111,DoS-UDP_Flood,1